version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "automated"
      - "dependencies"
    #reviewers:
    #  - "SilverKnightKMA"
    assignees:
      - "SilverKnightKMA"
