name: Auto Merge Flake Update PR

on:
  #check_suite:
  #  types:
  #    - completed
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    #if: github.event.pull_request.user.login == 'SilverKnightKMA'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_LABELS: "automated"
