name: "Flake.lock: Check Nix dependencies"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00

jobs:
  nix-flake-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
